name: Shell Commands

# on: [push, pull_request]
# can also pass the on as an object 
on:
  push:
  pull_request:
    # can activity types
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
          yarn -v
      # run on different OS shells
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
  run-windows-commands-in-series:
    runs-on: windows-latest
    needs: ["run-windows-commands"]
    steps:
      - name: Directory PowerShell
        run: ipconfig
      - name: Directory Bash
        run: pwd
        shell: bash